### ISSUE TITLE
No student files shown when a course is restored from a moodle backup

### ISSUE THREAD

**Issue by markchaneyuk** [academic-moodle-cooperation/moodle-mod_publication#13] opened 2016-03-21 09:31 UTC
We have done a backup of a course and restored this in another of our Moodles. In the original, two students (A & B) had uploaded files (2 each) and these files were all visible on mod/publication/view.php? page. The submissions showed in the _Last Modified_ column. The course was backed up and the backup file was restored on an identical Moodle(identical in code, environment but not necessarily settings or data). The students are visible in the restored course as whole and show up in the student folder ok. Logged in as a teacher the two students (A and B) are listed in the activity, as these are the only ones who submitted these are the only ones to show up. In the column _Last Modified_ no files are shown. If the _Download all Files as Zip_ is selected, then the files are present. This shows that the files are being backed up, and are being restored, but they are not being presented correctly. Let me know if you need anything else. Thanks.

**Comment by mchaney2010** [comment] 2016-03-21 09:43
Apologies: Moodle 2.7, soon to be upgraded to Moodle 3

**Comment by kaspot** [comment] 2016-03-23 04:27
Hi Mark, 
thanks for your feedback. May I ask you what exactly CBA is? And the second question would be: How does Moodle standard Quiz deal with this? We are trying to be as close to Moodle Core as possible, so it would be really useful to know how Moodle Core behaves. 
Thanks.

**Comment by kaspot** [comment] 2016-03-23 04:46
Thanks for reporting this. We will forward it to our developer to check the issue.

**Comment by soniaarnanz** [comment] 2016-04-14 15:03
We think the problem is the field mdl_files.itemid. This field means to be the userid but this is copied and restoree with the original value. In the restore process this field should match with the correct userid.
For this reason the file is linked with the course and with the module but not with the user who uploaded the file.
Thanks

**Comment by mkemmerling** [comment] 2016-06-06 08:14
The problem has been be fixed in the MOODLE_29_ STABLE branch as well as in the master and the new MOODLE_30_STABLE branches.

**Closed by mkemmerling** 2016-06-06 08:14 UTC
