### ISSUE TITLE
Issue with opening Zip file that is downloaded using the 'Download all files Zip' (top right hand corner)

### ISSUE THREAD

**Issue by AjmalSultany** [academic-moodle-cooperation/moodle-mod_publication#8] opened 2015-10-23 13:31 UTC
During testing we have found that the Zip file downloaded is corrupt and will not open (please see IMAGE 1 for error message).
The issue is only present when downloading the ZIP file using the link on the top right hand corner of the page (see IMAGE 2), and not with the bulk action. 
This is the case in both modes: assignment and folder.

Ajmal Sultany
University of Cambridge

![image 1_student folder](https://cloud.githubusercontent.com/assets/15264608/10693825/a4ce0940-7992-11e5-904c-1f69282009b6.png)
![image 2_student folder](https://cloud.githubusercontent.com/assets/15264608/10693827/a87c0902-7992-11e5-841f-10658c1e9c10.png)

**Comment by kaspot** [comment] 2015-10-29 06:28
Thanks for reporting this issue. May I ask you which moodle version you are running?

**Comment by AjmalSultany** [comment] 2015-10-29 09:33
Sure, we are on 2.7.7

**Comment by kaspot** [comment] 2015-10-29 14:47
and sorry for asking but are you using the right 2.7 version of the module? I can't really test it on this moodle version but I just tested it on moodle 2.8.5 and it seems to work fine there.

**Comment by AjmalSultany** [comment] 2015-10-30 07:38
No problem. We are using version: 2014113000 pulled through Moodle.org

**Comment by phager-at** [comment] 2015-11-03 10:47
I was able to reproduce the bug and it is due to a not created variable with throws a warning. This warning gets output in the ZIP file and corrupts it.

Workaround for now until we fixed the issue: deactivate the DEBUG output. The ZIP file should then be clean and usable again. If you just uncheck the checkbox for "Display debug messages" under admin/settings.php?section=debugging the debug messages get written to the PHP Error log and you can still access it without them interrupting ZIP-File creation.

**Comment by AjmalSultany** [comment] 2015-11-03 11:45
Hello. Thank you for the update and the proposed workaround. At the moment we are testing it in our dev environment which has debugging on. We will be going live with this plugin in early next year. Do you know when you will update the code either through Moodle.org or Github?

Thanks,

**Comment by kaspot** [comment] 2015-11-04 09:02
The fix should definitely be available for the newest 2.9, which we plan to release at the end of February. We will also fix it for the current 2.8 version.

**Comment by phager-at** [comment] 2015-11-12 20:29
@AjmalSultany INOFFICIAL & UNTESTED:
Fix for 2.7, because we will only fix and test it for 2.8 onwards as kaspot said. But I highly recommend to wait and use v2.8 and a Moodle 2.8 environment, that fix should soon be integrated.
https://github.com/academic-moodle-cooperation/moodle-mod_publication/pull/9

**Comment by mkemmerling** [comment] 2015-12-18 15:01
This has been fixed in the master and MOODLE_28_STABLE branches (version 2015100803). See the above comment for an inofficial fix for the MOODLE_27_STABLE branch.

**Closed by mkemmerling** 2015-12-18 15:01 UTC

**Comment by AjmalSultany** [comment] 2016-01-12 10:17
Thanks for this rapid response. I have made a note of this for our upgrade in the summer.

Best wishes,

Ajmal
