### ISSUE TITLE
Notification to trainer

### ISSUE THREAD

**Issue by eLearning-Group** [academic-moodle-cooperation/moodle-mod_publication#68] opened 2023-02-03 13:11 UTC
Under Notifications:
"Notify rater about uploads" is sent not only to the people with role trainer in the course but to all people with role trainer on the parent course area. 
This is wrong in my opinion. Only people who are enrolled in the course should be notified.

Kind regards Gabriella

**Comment by goggo24** [comment] 2023-02-06 08:58
Thanks for reporting. We will have a look. Which version of publication are you using?

**Comment by HWZElearning** [comment] 2023-02-06 09:03
pls see the attachement :-). Kind regards Gabriella
![Studierendenordner](https://user-images.githubusercontent.com/83763638/216929544-6ddc213b-ada3-45bb-8e5e-fe53707cd867.JPG)

**Comment by eLearning-Group** [comment] 2023-04-28 11:37
I saw I had tranlate the "Kursbereich" with a wrong word. It is the course categorie, not "course area".

We did update our system to moodle 4.1. And we also updated the plugin to v4.1.0 2022121200. But I have still the same problem. I have a course with some trainers whit role "trainer" and on the course categorie there is an other trainer with role "manager" and both get the message, when a student did upload something.

**Comment by goggo24** [comment] 2023-04-28 12:36
Thanks for the feedback. We will have a deeper look in 4.1.x of our plugin, because we tested it with 3.11.x and would come back to you, if we cannot reproduce it by ourselves.

**Comment by lukaslangkissC02** [comment] 2023-09-19 13:39
The problem also exists on our instance. Trainers are notified who are not directly enrolled in the course.
Moodle: 4.1.4+ (Build: 20230728)
Plugin: v4.1.1 (2022121201)

**Comment by goggo24** [comment] 2023-11-09 16:54
We could reproduce the Bug and will add it to our backlog.

**Comment by goggo24** [comment] 2023-12-06 04:38
The fix will be included in our next minor release - 4.2.2.

**Closed** 2023-12-11 17:28 UTC
Labels: bug, roadmap
