### ISSUE TITLE
Coding error by using Download all file submissions

### ISSUE THREAD

**Issue by Clarence71** [academic-moodle-cooperation/moodle-mod_publication#78] opened 2024-01-11 09:58 UTC
Hi,
we upgraded Moodle to 4.3.2 (from 3.11 over 4.0 ...)
installed Student Folder Plugin 4.2.2 and all works fine except the all file button.
error message: get_all_user_name_fields() is deprecated. Please use the \core_user\fields API instead
any known issues or solutions?
I am writing from Germany
Greetings Lars

**Comment by goggo24** [comment] 2024-01-11 10:37
We found the bug too ;) We are currently working on v.4.3.0 and we will publish this version in the next  2 weeks.  Is the fix urgent? If yes, we can make our current development branch available here via github, but without garanty. Regards, Eva

**Comment by Clarence71** [comment] 2024-01-19 06:50
Hi Eva,
do you have any (good) news for me?
we would also try developer inputs, if you have some.
Lars

**Comment by goggo24** [comment] 2024-01-19 07:26
We fixed the bug already, it's will be included in v.4.3.0.

**Comment by goggo24** [comment] 2024-02-12 19:33
Since last week v.4.3.0 from publication is available. Have fun!

**Comment by wiebkemueller-hsh** [comment] 2024-02-13 11:50
Dear @goggo24  Eva, will this be backported to 4.1.9? We're still using this LTS Version of Moodle. Thank you for considering! Wiebke

**Comment by goggo24** [comment] 2024-02-13 12:07
@wiebkemueller-hsh this error occured as far as we know only under Moodle 4.3.x. I've just tested it on our testenvironment under 4.1.6+ and 4.2.3 - there it worked fine. Can you give me some additional information - which version of publication do you use? If you press the link "Download all files as ZIP" the error occurs? Which mode do you use (upload or assignment)?

**Comment by wiebkemueller-hsh** [comment] 2024-02-13 12:26
Hi @goggo24 thanks for the super quick reply. 

We are testing [Moodle](http://moodle.org/) [4.1.9 (Build: 20240212] today and have installed mod_publication
v4.1.1
2022121201

When I click on "Download all" I get
get_all_user_name_fields() is deprecated. Please use the \core_user\fields API instead
line 3280 of /lib/deprecatedlib.php: call to debugging()
line 983 of /mod/publication/locallib.php: call to get_all_user_name_fields()
line 129 of /mod/publication/view.php: call to publication->download_zip()

Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/lib/weblib.php:3389) in /var/www/html/lib/filelib.php on line 2399

see also screenshot attached.
![1_mod-pub](https://github.com/academic-moodle-cooperation/moodle-mod_publication/assets/72548805/02f6f822-0a1c-4172-8ba4-8cade5b13693)


Thank you
Wiebke

**Comment by goggo24** [comment] 2024-02-13 13:32
Okay, thanks for the fast feedback - we will have a look.

**Comment by wiebkemueller-hsh** [comment] 2024-02-21 09:49
Hi Eva, 

@goggo24 

Just to let you know: For whatever reason the problem didn't occur anymore in our live system that is configured with the same parameters as the test system mentioned above. (?)

Regards!
Wiebke

**Comment by goggo24** [comment] 2024-02-21 18:56
@wiebkemueller-hsh good to know ;) As we already mentioned, we couldn't reproduce the bug and don't get the deprecated message nor the warning. We also tried it on another system, but the same behaviour . We are currently checking the code directly. If we find something, we'll let you know, but as it works on your production system, we will not give it a high priority.

**Closed** 2024-08-07 09:16 UTC
Labels: bug, roadmap
