### ISSUE TITLE
Feature Request: Only students with access appear in files list

### ISSUE THREAD

**Issue by WireLiz** [academic-moodle-cooperation/moodle-mod_publication#67] opened 2023-01-24 09:27 UTC
Hi everyone,

We are using the student folder module with moodle 3.9.19+

Our scenario: We manage several groups of students in a Moodle course. Each group has their own section, i.e. access for each section is restricted to one group. In each section there is (among other materials) a student folder. The student folders show all course participants for the trainer. It makes no difference whether we add an access restriction for the activity or not. Our wish would be that the student folder - just like in the activity "assignment" - only shows the participants in the files list who have access to the activity. 

Our workaround: The student folders are in "separate groups" mode and the trainer has to set the filter to the correct group. 
We would be glad to get rid of the workaround :)

Best wishes,
WireLiz

**Comment by goggo24** [comment] 2023-02-23 10:31
Thanks for reporting - I can reproduce the behaviour and will add it to our backlog.

**Comment by WireLiz** [comment] 2023-03-08 09:09
Great, Thanks very much.

**Comment by goggo24** [comment] 2023-12-06 04:36
The feature will be included in our next major release - 4.3.0

**Comment by goggo24** [comment] 2024-02-12 19:35
We have postponed the development to the next version, because it would have meant major changes to the plugin.

**Comment by mwreichel** [comment] 2024-08-07 09:35
Hi @WireLiz ,
good news: the feature is implemented in the new version (for Moodle 4.4).

All the best,
Martin

**Closed by mwreichel** 2024-08-07 09:35 UTC
Labels: enhancement, roadmap

**Comment by WireLiz** [comment] 2024-08-07 11:23
Hi Martin,

Thank you very much! That's good news indeed! :)

Best regards, Liz
