### ISSUE TITLE
Is this correct?

### ISSUE THREAD

**Issue by dinism** [academic-moodle-cooperation/moodle-mod_publication#25] opened 2018-01-14 13:10 UTC
Theme Boost

![imagem](https://user-images.githubusercontent.com/14828021/34916212-42babe80-f92c-11e7-82b2-fa14fc1254f6.png)

**Comment by goggo24** [comment] 2018-01-16 09:10
Thanks for the feedback - in our version it looks fine, also with standard boost.
Can you please tell us which versions you use? From Moodle Core, Themen Boost plugin and publication. So that we can reproduce the bug.

**Comment by dinism** [comment] 2018-01-16 13:44
![imagem](https://user-images.githubusercontent.com/14828021/34991943-523b502a-fac3-11e7-99e3-2fdd46ce4736.png)

**Comment by dinism** [comment] 2018-01-16 13:45
![imagem](https://user-images.githubusercontent.com/14828021/34991973-70e2292c-fac3-11e7-89dc-32f67d9c5d66.png)

**Comment by phager-at** [comment] 2018-01-16 17:44
Hi dinism,

I couldn't reproduce the seen bug on my machine (Moodle 3.4.1, mod_publication 3.4.0, theme boost). Do you have an description/intro text set? Is there maybe broken HTML in it?

cheers,
Philipp

**Comment by dinism** [comment] 2018-01-16 18:11
NO for 2 options. 
I will dig in it and try to discover.

**Comment by dinism** [comment] 2018-01-17 22:40
What i found. When END date to UPLOAD is enable BUMP.
---------------------------------------------------------------------------------------------
**Disable**
![imagem](https://user-images.githubusercontent.com/14828021/35070940-fe0e3494-fbd6-11e7-81d9-acd6562738b7.png)
------------------------------------------------------------------------------------------------
**Enable**
![imagem](https://user-images.githubusercontent.com/14828021/35070973-168d9be0-fbd7-11e7-87d4-157dc4d3c9d8.png)

**Comment by dinism** [comment] 2018-01-18 19:08
Any help?

**Comment by goggo24** [comment] 2018-01-19 08:04
Sorry, we still cannot reproduce the bug. It looks fine with Moodle 3.4.1, mod_publication 3.4.0, theme boost .... hmmm .... which browser do you use? Can you try another browser? Which changes have you done in boost?
![boost](https://user-images.githubusercontent.com/16721900/35140317-0d3ea338-fcf7-11e7-98b3-8f22c6f79e43.png)

**Comment by dinism** [comment] 2018-01-19 08:30
Chrome and Firefox. Both with same error.
Nothing changed in Boost.
Same error with prior version of mod_publication (not 3.4.0). 
In english and portuguese, the same error. :-1:

**Comment by phager-at** [comment] 2018-01-19 09:06
Hi again,

that's a very hard to track bug here... Can you open up the page (with the bug) and open Chrome's or Firefox's development tools and remove the classes and ID of the table containing the dates one by one and see if anyone of these changes happen to "fix" the bug?

And btw: what OS are you on?

Alternatetively can you name us every additional plugin you've got installed on your moodle installation?

**Comment by dinism** [comment] 2018-01-24 21:21
I outline the situation this way! Adding access restriction.
![imagem](https://user-images.githubusercontent.com/14828021/35357748-63f4591c-014c-11e8-8de1-2e683003ddfd.png)

**Comment by dinism** [comment] 2018-01-24 21:49
Take a look here:
https://imgur.com/a/tc8Vc

**Comment by goggo24** [comment] 2019-03-09 11:48
@dinism Does this behavior still occur to you? Or has an upgrade to moodle 3.5.x solved the problem.

**Comment by goggo24** [comment] 2020-02-24 17:28
@dinism: do you still have the problem? We still cannot reproduce it. 
If we don't get any feedback from you within this week, I will close the issue.

**Comment by MansouriAymen** [comment] 2020-11-19 10:06
add this code css in your moodle/mod/publication/style.css :
#dates.generalbox {
    height: auto;
}
that resolved the problem for me in moodle 3.9.

**Comment by goggo24** [comment] 2021-05-28 16:36
Thanks @MansouriAymen for sharing your workaround with us, so I will close this issue.

**Closed by goggo24** 2021-05-28 16:36 UTC
Labels: bug, question
