### ISSUE TITLE
Fehler: Class 'core_user\fields

### ISSUE THREAD

**Issue by Thiwico** [academic-moodle-cooperation/moodle-mod_publication#58] opened 2022-01-19 14:27 UTC
Hi everyone, I have the problem that the following error error: Class 'core_userfields appears.

I have updated from Moodle version 3.9 to 3.11.4.

Can anyone tell me how to solve this error.

Thank you for the help.

**Comment by goggo24** [comment] 2022-01-19 14:57
Why do you think it's a problem of the publication plugin? It looks like you have updated Moodle Core.

**Comment by goggo24** [comment] 2022-01-19 15:21
Can you send as a screenshot with the errormessage in publication activitiy, where the bug occurs?

**Comment by Thiwico** [comment] 2022-01-20 06:40
Good Morning,

her is the Screenshot.

<img width="676" alt="Screenshot 2022-01-20 073938" src="https://user-images.githubusercontent.com/82508582/150286687-04cfb821-c1df-418b-af5e-086cc04a624a.png">

**Comment by goggo24** [comment] 2022-02-09 06:06
Thanks for sending us the screenshot, we will have a look. Is it possible that you activate the debug mode and send us the detailed error message too? That would be great.

**Comment by Thiwico** [comment] 2022-02-09 07:54
No Problem.

Here is the screenshot from debugging.

![Error](https://user-images.githubusercontent.com/82508582/153145901-90b75f1e-ce59-4b44-89ec-17941af01f96.PNG)

**Comment by PhilipWaage** [comment] 2022-03-04 09:00
**Did anything come up in solving this problem? I am now facing the same problem.** 
Unfortunately, other plugins do not meet the requirements for the desired handling of the learners' files.

**Comment by goggo24** [comment] 2022-03-04 11:42
we will have a look next week and come back to you.

**Comment by PhilipWaage** [comment] 2022-03-28 09:57
> we will have a look next week and come back to you.

**Is there any idea to handle this problem?**

**Comment by goggo24** [comment] 2022-03-29 07:51
Sorry for not having an answer, but i'm still waiting for an answer myself.

**Comment by moniNaydenov** [comment] 2022-04-20 11:48
Hi,
We tested with 
- mod_publication version 2021052502 / 2021052503 (not yet published)
- moodle 3.11.6+ 2021051706

The core_user\fields is not yet deprecated and the module is working without problems. core_user\fields gets deprecated in 4.0, so the issue will be fixed for 4.0

Best regards!

**Comment by PhilipWaage** [comment] 2022-04-21 09:28
Thanks for your answer. 
Moodle has now been updated at our educational institution and now this plugin works.

**Comment by Thiwico** [comment] 2022-04-22 06:53
Thanks for the Answer.

For me that solved the problem.

After updating the plugin.
Errors are no longer displayed.

I thank you for the help.

**Comment by Thiwico** [comment] 2022-04-22 07:03
Okay, after testing various things, this error appears when I create a new folder.

![grafik](https://user-images.githubusercontent.com/82508582/164622620-f900c105-b921-46e1-a4f4-bd88f038cff5.png)

**Comment by Thiwico** [comment] 2022-04-22 07:04
Existing folders, the problem is gone.

**Comment by Thiwico** [comment] 2022-04-22 07:08
Okay think first and then write.

So the problem is still there.

Unfortunately, I lost my eye and was on delivery.

I apologize for the confusion.

**Comment by goggo24** [comment] 2022-04-22 07:16
It should work with 3.11.4+ too, but if you have the opportunity to upgrade Moodle Core easily, pleaste try it. Thanks.

**Comment by Thiwico** [comment] 2022-04-22 07:22
Many thanks for the answer.

I will test this on Sunday.

My question is, should I go straight to version 4 or 3.11.6+?

**Comment by goggo24** [comment] 2022-04-22 07:30
As we know, our plugin isn't working correctly with Core 4.0.0 - as mentioned from @moniNaydenov we are just working on a 4.0. compatible version. Please be patient - coming soon ;) So I would only update to 3.11.6+, because with 4.0 also a lot of layout changes in general in Moodle appear and at the moment not all additional plugins are compatible.

**Comment by Thiwico** [comment] 2022-04-24 12:23
I have now updated Moodle to the latest 3.11.6+ 20220423 Version.

I then uninstalled and reinstalled the plugin.

The error stays the same.

![image](https://user-images.githubusercontent.com/82508582/164976199-d25f329b-a3f9-426e-96c2-7528c4ae65b6.png)

Any idea why the plugin is still not working for me?

**Comment by goggo24** [comment] 2022-05-25 22:09
@Thiwico which version of the publication plugin do you use? We cannot reproduce the bug.

**Comment by goggo24** [comment] 2022-06-13 06:27
v.4.0.0 of publication just publised. Have fun!

**Closed by goggo24** 2022-06-13 06:27 UTC
Labels: bug
